// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: internal/pb/response.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Segment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Airports are IATA codes; the full names appear only in the JSON. Times
	// are ISO-8601 with the local UTC offset.
	FromAirport   string `protobuf:"bytes,1,opt,name=from_airport,json=fromAirport,proto3" json:"from_airport,omitempty"`
	DepartureTime string `protobuf:"bytes,2,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ToAirport     string `protobuf:"bytes,3,opt,name=to_airport,json=toAirport,proto3" json:"to_airport,omitempty"`
	ArrivalTime   string `protobuf:"bytes,4,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	Airline       string `protobuf:"bytes,5,opt,name=airline,proto3" json:"airline,omitempty"`
	FlightNumber  string `protobuf:"bytes,6,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	// Duplicates airline/flight_number in every sample observed, including
	// true codeshares — where the operator ("SkyWest Airlines as American
	// Eagle") appears only in the JSON. Not the operating airline.
	TicketingAirline      string `protobuf:"bytes,7,opt,name=ticketing_airline,json=ticketingAirline,proto3" json:"ticketing_airline,omitempty"`
	TicketingFlightNumber string `protobuf:"bytes,8,opt,name=ticketing_flight_number,json=ticketingFlightNumber,proto3" json:"ticketing_flight_number,omitempty"`
	Class                 Class  `protobuf:"varint,9,opt,name=class,proto3,enum=Class" json:"class,omitempty"`
	// IATA aircraft type code, e.g. "321". The JSON spells it "Airbus A321".
	Aircraft      string `protobuf:"bytes,10,opt,name=aircraft,proto3" json:"aircraft,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Segment) Reset() {
	*x = Segment{}
	mi := &file_internal_pb_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Segment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segment) ProtoMessage() {}

func (x *Segment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segment.ProtoReflect.Descriptor instead.
func (*Segment) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{0}
}

func (x *Segment) GetFromAirport() string {
	if x != nil {
		return x.FromAirport
	}
	return ""
}

func (x *Segment) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *Segment) GetToAirport() string {
	if x != nil {
		return x.ToAirport
	}
	return ""
}

func (x *Segment) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *Segment) GetAirline() string {
	if x != nil {
		return x.Airline
	}
	return ""
}

func (x *Segment) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *Segment) GetTicketingAirline() string {
	if x != nil {
		return x.TicketingAirline
	}
	return ""
}

func (x *Segment) GetTicketingFlightNumber() string {
	if x != nil {
		return x.TicketingFlightNumber
	}
	return ""
}

func (x *Segment) GetClass() Class {
	if x != nil {
		return x.Class
	}
	return Class_CLASS_UNSPECIFIED
}

func (x *Segment) GetAircraft() string {
	if x != nil {
		return x.Aircraft
	}
	return ""
}

// Slice is one direction of travel. Only ever one per token so far: a round
// trip search returns tokens for the outbound leg, and the return is chosen
// against a follow-up request.
type Slice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*Segment             `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Slice) Reset() {
	*x = Slice{}
	mi := &file_internal_pb_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{1}
}

func (x *Slice) GetSegments() []*Segment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type Airlines struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display names in segment order, e.g. ["Alaska", "Condor"].
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Airlines) Reset() {
	*x = Airlines{}
	mi := &file_internal_pb_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Airlines) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Airlines) ProtoMessage() {}

func (x *Airlines) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Airlines.ProtoReflect.Descriptor instead.
func (*Airlines) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{2}
}

func (x *Airlines) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type PassengerCount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Confirmed by varying the request: 3 is an adult and 2 is a child. Note
	// this does not match the request's Passenger enum, where ADULT is 1.
	// Infant values were not observed.
	Type          int32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Count         int32 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PassengerCount) Reset() {
	*x = PassengerCount{}
	mi := &file_internal_pb_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PassengerCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PassengerCount) ProtoMessage() {}

func (x *PassengerCount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PassengerCount.ProtoReflect.Descriptor instead.
func (*PassengerCount) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{3}
}

func (x *PassengerCount) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *PassengerCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Fare struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Amount in the currency's minor units, scaled by decimal_digits, so
	// 19920 with 2 digits is 199.20. The JSON rounds this to whole units.
	Amount        int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fare) Reset() {
	*x = Fare{}
	mi := &file_internal_pb_response_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fare) ProtoMessage() {}

func (x *Fare) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fare.ProtoReflect.Descriptor instead.
func (*Fare) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{4}
}

func (x *Fare) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Trip struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Slices     []*Slice               `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	Passengers []*PassengerCount      `protobuf:"bytes,2,rep,name=passengers,proto3" json:"passengers,omitempty"`
	// Always 1 and 0 respectively across every sample. Marked optional so the
	// explicit zero survives a re-encode, which proto3 would otherwise drop.
	Unknown_3     *int32    `protobuf:"varint,3,opt,name=unknown_3,json=unknown3,proto3,oneof" json:"unknown_3,omitempty"`
	Unknown_5     *int32    `protobuf:"varint,5,opt,name=unknown_5,json=unknown5,proto3,oneof" json:"unknown_5,omitempty"`
	Airlines      *Airlines `protobuf:"bytes,6,opt,name=airlines,proto3" json:"airlines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_internal_pb_response_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{5}
}

func (x *Trip) GetSlices() []*Slice {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *Trip) GetPassengers() []*PassengerCount {
	if x != nil {
		return x.Passengers
	}
	return nil
}

func (x *Trip) GetUnknown_3() int32 {
	if x != nil && x.Unknown_3 != nil {
		return *x.Unknown_3
	}
	return 0
}

func (x *Trip) GetUnknown_5() int32 {
	if x != nil && x.Unknown_5 != nil {
		return *x.Unknown_5
	}
	return 0
}

func (x *Trip) GetAirlines() *Airlines {
	if x != nil {
		return x.Airlines
	}
	return nil
}

type BookingToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Decimal places for fare amounts: 2 for USD, 0 for JPY. Optional because
	// the zero is written explicitly and must survive a re-encode.
	DecimalDigits *int32 `protobuf:"varint,1,opt,name=decimal_digits,json=decimalDigits,proto3,oneof" json:"decimal_digits,omitempty"`
	Currency      string `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Fare          *Fare  `protobuf:"bytes,3,opt,name=fare,proto3" json:"fare,omitempty"`
	Trip          *Trip  `protobuf:"bytes,4,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingToken) Reset() {
	*x = BookingToken{}
	mi := &file_internal_pb_response_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingToken) ProtoMessage() {}

func (x *BookingToken) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_response_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingToken.ProtoReflect.Descriptor instead.
func (*BookingToken) Descriptor() ([]byte, []int) {
	return file_internal_pb_response_proto_rawDescGZIP(), []int{6}
}

func (x *BookingToken) GetDecimalDigits() int32 {
	if x != nil && x.DecimalDigits != nil {
		return *x.DecimalDigits
	}
	return 0
}

func (x *BookingToken) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BookingToken) GetFare() *Fare {
	if x != nil {
		return x.Fare
	}
	return nil
}

func (x *BookingToken) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

var File_internal_pb_response_proto protoreflect.FileDescriptor

var file_internal_pb_response_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61, 0x69, 0x72, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x41,
	0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74,
	0x75, 0x72, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x69, 0x72, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2b,
	0x0a, 0x11, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x61, 0x69, 0x72, 0x6c,
	0x69, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x74, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x69, 0x6e, 0x67, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x74,
	0x69, 0x63, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x74, 0x69,
	0x63, 0x6b, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x46, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x06, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x69, 0x72, 0x63, 0x72, 0x61, 0x66, 0x74, 0x22, 0x2d, 0x0a,
	0x05, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x12, 0x24, 0x0a, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x53, 0x65, 0x67, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x08, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x20, 0x0a, 0x08,
	0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22, 0x3a,
	0x0a, 0x0e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x1e, 0x0a, 0x04, 0x46, 0x61,
	0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xde, 0x01, 0x0a, 0x04, 0x54,
	0x72, 0x69, 0x70, 0x12, 0x1e, 0x0a, 0x06, 0x73, 0x6c, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x53, 0x6c, 0x69, 0x63, 0x65, 0x52, 0x06, 0x73, 0x6c, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e, 0x67, 0x65, 0x72,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x0a, 0x70, 0x61, 0x73, 0x73, 0x65, 0x6e,
	0x67, 0x65, 0x72, 0x73, 0x12, 0x20, 0x0a, 0x09, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f,
	0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x08, 0x75, 0x6e, 0x6b, 0x6e, 0x6f,
	0x77, 0x6e, 0x33, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x6e, 0x5f, 0x35, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x08, 0x75, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x6e, 0x35, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x08, 0x61, 0x69, 0x72, 0x6c,
	0x69, 0x6e, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x41, 0x69, 0x72,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x08, 0x61, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x33, 0x42, 0x0c, 0x0a,
	0x0a, 0x5f, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x35, 0x22, 0x9f, 0x01, 0x0a, 0x0c,
	0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2a, 0x0a, 0x0e,
	0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x44,
	0x69, 0x67, 0x69, 0x74, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x12, 0x19, 0x0a, 0x04, 0x66, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x46, 0x61, 0x72, 0x65, 0x52, 0x04, 0x66, 0x61, 0x72, 0x65, 0x12,
	0x19, 0x0a, 0x04, 0x74, 0x72, 0x69, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x54, 0x72, 0x69, 0x70, 0x52, 0x04, 0x74, 0x72, 0x69, 0x70, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x5f, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x42, 0x2b, 0x5a,
	0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x78, 0x6d,
	0x77, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x66, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
})

var (
	file_internal_pb_response_proto_rawDescOnce sync.Once
	file_internal_pb_response_proto_rawDescData []byte
)

func file_internal_pb_response_proto_rawDescGZIP() []byte {
	file_internal_pb_response_proto_rawDescOnce.Do(func() {
		file_internal_pb_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_response_proto_rawDesc), len(file_internal_pb_response_proto_rawDesc)))
	})
	return file_internal_pb_response_proto_rawDescData
}

var file_internal_pb_response_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_pb_response_proto_goTypes = []any{
	(*Segment)(nil),        // 0: Segment
	(*Slice)(nil),          // 1: Slice
	(*Airlines)(nil),       // 2: Airlines
	(*PassengerCount)(nil), // 3: PassengerCount
	(*Fare)(nil),           // 4: Fare
	(*Trip)(nil),           // 5: Trip
	(*BookingToken)(nil),   // 6: BookingToken
	(Class)(0),             // 7: Class
}
var file_internal_pb_response_proto_depIdxs = []int32{
	7, // 0: Segment.class:type_name -> Class
	0, // 1: Slice.segments:type_name -> Segment
	1, // 2: Trip.slices:type_name -> Slice
	3, // 3: Trip.passengers:type_name -> PassengerCount
	2, // 4: Trip.airlines:type_name -> Airlines
	4, // 5: BookingToken.fare:type_name -> Fare
	5, // 6: BookingToken.trip:type_name -> Trip
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_pb_response_proto_init() }
func file_internal_pb_response_proto_init() {
	if File_internal_pb_response_proto != nil {
		return
	}
	file_internal_pb_request_proto_init()
	file_internal_pb_response_proto_msgTypes[5].OneofWrappers = []any{}
	file_internal_pb_response_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_response_proto_rawDesc), len(file_internal_pb_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_pb_response_proto_goTypes,
		DependencyIndexes: file_internal_pb_response_proto_depIdxs,
		MessageInfos:      file_internal_pb_response_proto_msgTypes,
	}.Build()
	File_internal_pb_response_proto = out.File
	file_internal_pb_response_proto_goTypes = nil
	file_internal_pb_response_proto_depIdxs = nil
}
